# Generated by Django 4.1.1 on 2022-10-18 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendnce',
            new_name='attendance',
        ),
    ]
